### ISSUE TITLE
domainname\username is not working

### ISSUE THREAD

**Issue by swethajdev** [EliteLoser/SSHSessions#5]
domainname\username is not working for new-SSHSession

**Comment by EliteLoser** [comment]
Please provide more information.

Is it an AD-integrated winbind/kerberos-based authentication scheme on the remote (Linux? what distro and version?) host that's not working against your Active Directory with this module?

Including the error message and a description of how it fails would be useful...

Normally with SSH you use the form user@domain.

**Comment by EliteLoser** [comment]
I'll just close this for now due to lack of feedback and me not being able to make sense of the request. My mind "instantly" concocted an idea to just swap it around for people, from domain\user to user@domain, whenever the former was provided, but it seems a bit odd. Unsure. Closing for now. Re-open and provide more detail if necessary.
