### ISSUE TITLE
Local variable cannot be passed to the session when I use $Using

### ISSUE THREAD

**Issue by GeethaSelvam** [EliteLoser/SSHSessions#6]
Argument List and $Using variables are not accepted by Invoke-SshCommand.
Please share an example how to pass local variable to ScriptBlock in Invoke-SshCommand

**Comment by EliteLoser** [comment]
I haven't had a chance to use this myself in years now to be honest. I think it should just work if you put `$PlainOldVariable` there directly. Let me know. Thought this didn't work against newer Linux distros because of an old DLL. Idk. Years since I had a chance to even test it. Have an old version running in production code somewhere, successfully still.

**Comment by EliteLoser** [comment]
I looked at the code. If you specify a -ScriptBlock, the .ToString() method will be run on it, as per: https://github.com/EliteLoser/SSHSessions/blob/master/SSHSessions.psm1#L311 -- So you can use -Command and specify it directly, or -ScriptBlock and have whatever .ToString() behaviour is used on the variable. Very little feedback on this module in general. Not sure how people use it.

**Comment by GeethaSelvam** [comment]
Hi EliteLoser,
    I cannot understand what does $PlainOldVariable means
I am trying to run the following
$s="example"
Invoke-SSHCommand -ComputerName abc  -ScriptBlock{echo $Using:s}
(or)
Invoke-SSHCommand -ComputerName abc  -ScriptBlock{echo $s}
Both didnt work

**Comment by EliteLoser** [comment]
Can you try `Invoke-SSHCommand -ComputerName abc -Command "echo $s"`? I think there are a lot of edge cases here I should smooth out, but you're my first feedback!

**Comment by GeethaSelvam** [comment]
Great!! This is working...Also can I use -Command for sending a sequence of commands by using a ; between each command?

**Comment by GeethaSelvam** [comment]
Thanks a lot!! - Command works for sequence of commands also.. I just checked

**Comment by EliteLoser** [comment]
That's good. Guess I can close the issue. Can I ask which Linux distro you're using it against? I got a mail through the PowerShell Gallery maybe a year ago in a slightly confusing way that said something about an error I remember before - and I had to update the DLL to support newer distributions.

Maybe there are now "pseudo blog posts" about this module (for sure) that say how to use it for such and such purposes. I saw some already back almost 10 years ago. Before the "competitor" PoSH-SSH showed up. Are you using a newer DLL or the one from this repository on GitHub (or in the PowerShell Gallery)? Just a "default install"? Or did you follow instructions to obtain a newer DLL? This has been pestering me in the back of my mind since I got that mail a long while ago.
